CREATE TABLE search_results (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
town VARCHAR(30) NOT NULL,
from_date VARCHAR(30) NOT NULL,
to_date VARCHAR(30) NOT NULL,
ip_address VARCHAR(30) NOT NULL 
)